services:
  mysql:
    image: 'mysql:8.3.0'
    container_name: ordforandeDB
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
    ports:
      - '3306:3306'

    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ordforandelista
    ports:
      - '9001:9001'
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
